# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22fa09184ab41d0849f1f3b3ba091cd5dec4db102109bb9d8fb6230b06803c8dc2528fb7795deab50bacfba132224316e646733e08132ac944eaf485627af458

test:
  secret_key_base: 57793231544603c2f17cee281fd71dd4e8ec24a79862cb892d49f5cd6bc157bb970ec921339c5e5fcaad134fdd2540c7f37be2e8a9366a296c22c4e560899873

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
